using JurassicPark.Core;
using UnityEngine;

namespace JurassicPark.World
{
    public enum PropKind
    {
        Tree,
        Rock,
        Grass,
        Log,
        Bush,
    }

    /// <summary>One prop sprite with its footprint and what it yields. Several variants per kind keep the island from repeating.</summary>
    [CreateAssetMenu(menuName = "Jurassic Park/Prop Variant", fileName = "Prop")]
    public sealed class PropVariant : ScriptableObject
    {
        public PropKind kind = PropKind.Tree;
        public Texture2D sprite;
        [Tooltip("Sprite cell size in pixels; height in meters is cell / pixelsPerUnit.")]
        [Min(8)] public int cellPixels = 128;
        [Min(1f)] public float pixelsPerUnit = 64f;
        [Tooltip("Radius on the ground other props and structures keep clear, in meters at scale 1.")]
        [Min(0f)] public float footprintRadius = 0.6f;
        [Tooltip("Blocks movement and carves the NavMesh.")]
        public bool solid = true;
        public ResourceKind resource = ResourceKind.None;
        [Min(0)] public int resourceAmount = 0;
        [Tooltip("Relative chance when a kind is picked at random.")]
        [Min(0f)] public float weight = 1f;

        [Tooltip("One material per library tint, generated by build_prop_library. Shared so the SRP batcher can draw all instances of a variant together.")]
        public Material[] tintMaterials = new Material[0];
        [Tooltip("Material shown while the resource node is depleted.")]
        public Material depletedMaterial;

        public float HeightMeters => cellPixels / pixelsPerUnit;

        public Material MaterialFor(int tintIndex)
        {
            if (tintMaterials == null || tintMaterials.Length == 0) return null;
            return tintMaterials[Mathf.Clamp(tintIndex, 0, tintMaterials.Length - 1)];
        }
    }
}
